export interface encuesta1{
cedula:number
fecha_aplicacion:Date
nombre_encuestado:String
sexo:String
anio_nacimiento:Date
estado_civil:String
ult_niv_estudio:String
ocupacion_profesion:String
ciudad_residencia:String
departamento_residencia:String
estrato_servicios:String
tipo_vivienda:String
numero_personas_dependientes_econo:String
ciudad_trabajo:String
departamento_trabajo:String
anios_lleva_mas_menos_en_empresa:boolean
tiempo_en_empresa:String
nombre_cargo:String
cargo_mas_parecido:String
anios_mas_menos_en_cargo:boolean
anios_en_cargo_empresa:String
departamento_area_seccion_empresa:String
tipo_contrato:String
horas_trabajo_al_dia:String
tipo_salario_recibo:String
    
}
export interface encuesta2
{
    pregunta1:number
    pregunta2:number
    pregunta3:number
    pregunta4:number
    pregunta5:number
    pregunta6:number
    pregunta7:number
    pregunta8:number
    pregunta9:number
    pregunta10:number
    pregunta11:number
    pregunta12:number
    pregunta13:number
    pregunta14:number
    pregunta15:number
}
export interface encuesta3
{
    pregunta1:number
    pregunta2:number
    pregunta3:number
    pregunta4:number
    pregunta5:number
    pregunta6:number
    pregunta7:number
    pregunta8:number
    pregunta9:number
    pregunta10:number
    pregunta11:number
    pregunta12:number
    pregunta13:number
    pregunta14:number
    pregunta15:number
}
export interface encuesta4
{
    pregunta1:number
    pregunta2:number
    pregunta3:number
    pregunta4:number
    pregunta5:number
    pregunta6:number
    pregunta7:number
    pregunta8:number
    pregunta9:number
    pregunta10:number
    pregunta11:number
    pregunta12:number
    pregunta13:number
    pregunta14:number
    pregunta15:number
    pregunta16:number
    pregunta17:number
    pregunta18:number
    pregunta19:number
    pregunta20:number
    pregunta21:number
}
export interface encuesta5
{
    pregunta1:number
    pregunta2:number
    pregunta3:number
    pregunta4:number
    pregunta5:number
    pregunta6:number
    pregunta7:number
    pregunta8:number
    pregunta9:number
    pregunta10:number
    pregunta11:number
    pregunta12:number
    pregunta13:number
    pregunta14:number
}