export interface encuesta1{
cedula:number
nombre_encuestado:String
sexo:String
anio_nacimiento:Date
estado_civil:String
ult_niv_estudio:String
ocupacion_profesion:String
ciudad_residencia:String
departamento_residencia:String
estrato_servicios:String
tipo_vivienda:String
numero_personas_dependientes_econo:String
ciudad_trabajo:String
departamento_trabajo:String
anios_lleva_mas_menos_en_empresa:boolean
tiempo_en_empresa:String
nombre_cargo:String
cargo_mas_parecido:String
anios_mas_menos_en_cargo:boolean
anios_en_cargo_empresa:String
departamento_area_seccion_empresa:String
tipo_contrato:String
horas_trabajo_al_dia:String
tipo_salario_recibo:String
    
}
export interface encuesta2
{
    cedula:number
    e2_pregunta1:number
    e2_pregunta2:number
    e2_pregunta3:number
    e2_pregunta4:number
    e2_pregunta5:number
    e2_pregunta6:number
    e2_pregunta7:number
    e2_pregunta8:number
    e2_pregunta9:number
    e2_pregunta10:number
    e2_pregunta11:number
    e2_pregunta12:number
    e2_pregunta13:number
    e2_pregunta14:number
    e2_pregunta15:number
}
export interface encuesta3
{
    cedula:number
    e3_pregunta1:number
    e3_pregunta2:number
    e3_pregunta3:number
    e3_pregunta4:number
    e3_pregunta5:number
    e3_pregunta6:number
    e3_pregunta7:number
    e3_pregunta8:number
    e3_pregunta9:number
    e3_pregunta10:number
    e3_pregunta11:number
    e3_pregunta12:number
    e3_pregunta13:number
    e3_pregunta14:number
    e3_pregunta15:number
   
}
export interface encuesta4
{
    cedula:number
    e4_pregunta1:number
    e4_pregunta2:number
    e4_pregunta3:number
    e4_pregunta4:number
    e4_pregunta5:number
    e4_pregunta6:number
    e4_pregunta7:number
    e4_pregunta8:number
    e4_pregunta9:number
    e4_pregunta10:number
    e4_pregunta11:number
    e4_pregunta12:number
    e4_pregunta13:number
    e4_pregunta14:number
    e4_pregunta15:number
    e4_pregunta16:number
    e4_pregunta17:number
    e4_pregunta18:number
    e4_pregunta19:number
    e4_pregunta20:number
    e4_pregunta21:number
  
}
export interface encuesta5
{
    cedula:number
    e5_pregunta1:number
    e5_pregunta2:number
    e5_pregunta3:number
    e5_pregunta4:number
    e5_pregunta5:number
    e5_pregunta6:number
    e5_pregunta7:number
    e5_pregunta8:number
    e5_pregunta9:number
    e5_pregunta10:number
    e5_pregunta11:number
    e5_pregunta12:number
    e5_pregunta13:number
    e5_pregunta14:number
    
}